"""reconciliation_core

Revision ID: 20261007_0015
Revises: 20261007_0014
Create Date: 2026-10-07 16:01:00.242789
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20261007_0015"
down_revision: str | None = "20261007_0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint("ck_policy_version_type", "policy_versions", type_="check")
    op.create_check_constraint("ck_policy_version_type", "policy_versions", POLICY_TYPES_NEW)
    op.execute(RECON_POLICY_TRIGGER_FUNCTION)
    op.execute(
        "CREATE TRIGGER trg_recon_approved_policy BEFORE UPDATE OR DELETE ON "
        "policy_versions FOR EACH ROW EXECUTE FUNCTION badban_guard_recon_policy()"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reconciliation_type", sa.String(length=80), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("scope_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_identity", sa.String(length=64), nullable=False),
        sa.Column("source_content_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_pack_id", sa.UUID(), nullable=False),
        sa.Column("policy_pack_version", sa.Integer(), nullable=False),
        sa.Column("reconciliation_policy_version_id", sa.UUID(), nullable=False),
        sa.Column("reconciliation_policy_version_number", sa.Integer(), nullable=False),
        sa.Column("reconciliation_policy_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("rule_schema_version", sa.String(length=80), nullable=False),
        sa.Column("algorithm_code", sa.String(length=80), nullable=False),
        sa.Column("algorithm_version", sa.String(length=80), nullable=False),
        sa.Column("internal_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_cutoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_snapshot_ref", sa.String(length=500), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('COMPLETED','SOURCE_UNAVAILABLE')", name="ck_recon_run_status"
        ),
        sa.CheckConstraint(
            "policy_pack_version > 0 AND reconciliation_policy_version_number > 0",
            name="ck_recon_run_versions",
        ),
        sa.ForeignKeyConstraint(["policy_pack_id"], ["policy_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["provider_id"], ["credit_providers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reconciliation_policy_version_id"], ["policy_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_identity", name="uq_recon_run_source_identity"),
    )
    op.create_index(
        "ix_recon_runs_provider_started",
        "reconciliation_runs",
        ["provider_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "reconciliation_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("internal_entity_type", sa.String(length=80), nullable=False),
        sa.Column("internal_entity_id", sa.String(length=255), nullable=False),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("materiality", sa.String(length=20), nullable=False),
        sa.Column("mismatch_reason_code", sa.String(length=120), nullable=True),
        sa.Column("compared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_reference", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "materiality IN ('INFO','WARNING','MATERIAL','CRITICAL')",
            name="ck_recon_case_materiality",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','MATCHED','MISMATCH','STALE','DISPUTED','RESOLVED')",
            name="ck_recon_case_status",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["reconciliation_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recon_cases_run_status", "reconciliation_cases", ["run_id", "status"], unique=False
    )
    op.create_table(
        "reconciliation_blocks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reconciliation_case_id", sa.UUID(), nullable=False),
        sa.Column("blocked_command_type", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reconciliation_case_id"], ["reconciliation_cases.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reconciliation_case_id", "blocked_command_type", name="uq_recon_block_case_command"
        ),
    )
    op.create_table(
        "reconciliation_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reconciliation_case_id", sa.UUID(), nullable=False),
        sa.Column("internal_value_reference", sa.String(length=500), nullable=True),
        sa.Column("external_value_reference", sa.String(length=500), nullable=True),
        sa.Column("difference_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reconciliation_case_id"], ["reconciliation_cases.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.execute(
        "CREATE FUNCTION badban_reject_recon_history_mutation() RETURNS trigger AS "
        "$$ BEGIN RAISE EXCEPTION 'reconciliation history is append-only'; END; $$ "
        "LANGUAGE plpgsql"
    )
    for table in ("reconciliation_runs", "reconciliation_observations"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION badban_reject_recon_history_mutation()"
        )


def downgrade() -> None:
    # Preserve governed versions: downgrade must not delete policy content to fit the old schema.
    if (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM policy_versions WHERE policy_type = "
                "'RECONCILIATION_POLICY')"
            )
        )
        .scalar()
    ):
        raise RuntimeError(
            "Cannot downgrade while reconciliation policy versions exist; retain the "
            "schema and use a forward fix"
        )
    for table in ("reconciliation_runs", "reconciliation_observations"):
        op.execute(f"DROP TRIGGER trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION badban_reject_recon_history_mutation")
    op.execute("DROP TRIGGER trg_recon_approved_policy ON policy_versions")
    op.execute("DROP FUNCTION badban_guard_recon_policy")
    op.drop_constraint("ck_policy_version_type", "policy_versions", type_="check")
    op.create_check_constraint("ck_policy_version_type", "policy_versions", POLICY_TYPES_OLD)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reconciliation_observations")
    op.drop_table("reconciliation_blocks")
    op.drop_index("ix_recon_cases_run_status", table_name="reconciliation_cases")
    op.drop_table("reconciliation_cases")
    op.drop_index("ix_recon_runs_provider_started", table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    # ### end Alembic commands ###


POLICY_TYPES_OLD = (
    "policy_type IN ('ASSET_TYPE_POLICY','OWNERSHIP_FUNDING_POLICY',"
    "'PROVIDER_PRODUCT_POLICY','RISK_APPETITE_POLICY',"
    "'RETURN_ALLOCATION_POLICY','LEGAL_AUTHORIZATION_POLICY',"
    "'POSTING_ACCOUNTING_MAPPING_POLICY','PILOT_POLICY_PACK')"
)
POLICY_TYPES_NEW = POLICY_TYPES_OLD[:-1] + ", 'RECONCILIATION_POLICY')"
RECON_POLICY_TRIGGER_FUNCTION = """
CREATE FUNCTION badban_guard_recon_policy() RETURNS trigger AS $$
BEGIN
    IF OLD.policy_type = 'RECONCILIATION_POLICY' AND OLD.lifecycle_status IN
            ('APPROVED','ACTIVE','SUPERSEDED','RETIRED') THEN
        IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'approved reconciliation policy is
            immutable'; END IF;
        IF NEW.lifecycle_status NOT IN ('APPROVED','ACTIVE','SUPERSEDED','RETIRED') OR
           (to_jsonb(NEW) -
            ARRAY['lifecycle_status','version','updated_at','activated_at','superseded_at'])
            IS DISTINCT FROM
           (to_jsonb(OLD) -
            ARRAY['lifecycle_status','version','updated_at','activated_at','superseded_at'])
        THEN RAISE EXCEPTION 'approved reconciliation policy content is immutable'; END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""
